//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class article
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [MinLength(50, ErrorMessage = "greater must be greater than 50 words")]
        [Display(Name ="Article")]
        public string article1 { get; set; }
        public System.DateTime publishedOn { get; set; }
        [Required(ErrorMessage ="Title is a required field")]
        [MaxLength(30, ErrorMessage = "title must be less than 30 words")]
        public string title { get; set; }
    }
}
